import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import './global.css'

const roboto = Roboto({
  weight: ['400', '700'], 
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.className} bg-gray900 text-gray100 font-normal`}>
        {children}
      </body>
    </html>
  );
}
